[package]
name = "poetry-book"
version = "0.1.0"
authors = ["MarcoIeni"]
edition = "2018"
description = "Create a poetry book in latex, starting from plain text."
license = "MIT OR Apache-2.0"

[dependencies]
